-- ═══════════════════════════════════════════════════════════════════════════════
-- Spring Batch Enterprise Framework - Schema
-- ═══════════════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────────────────────
-- 배치 작업 이력 테이블 (커스텀)
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS BATCH_JOB_HISTORY (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_INSTANCE_ID BIGINT,
    JOB_EXECUTION_ID BIGINT,
    STATUS VARCHAR(50),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    READ_COUNT BIGINT DEFAULT 0,
    WRITE_COUNT BIGINT DEFAULT 0,
    SKIP_COUNT BIGINT DEFAULT 0,
    ERROR_MESSAGE VARCHAR(2500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100)
);

-- ───────────────────────────────────────────────────────────────────────────────
-- 배치 스케줄 관리 테이블
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS BATCH_SCHEDULE (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JOB_NAME VARCHAR(200) NOT NULL UNIQUE,
    CRON_EXPRESSION VARCHAR(100),
    ENABLED BOOLEAN DEFAULT TRUE,
    DESCRIPTION VARCHAR(500),
    LAST_EXECUTION_TIME TIMESTAMP,
    NEXT_EXECUTION_TIME TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
);

-- ───────────────────────────────────────────────────────────────────────────────
-- 배치 파라미터 설정 테이블
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS BATCH_PARAMETER (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JOB_NAME VARCHAR(200) NOT NULL,
    PARAM_KEY VARCHAR(100) NOT NULL,
    PARAM_VALUE VARCHAR(1000),
    PARAM_TYPE VARCHAR(50) DEFAULT 'STRING',
    DESCRIPTION VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UK_BATCH_PARAM UNIQUE (JOB_NAME, PARAM_KEY)
);

-- ───────────────────────────────────────────────────────────────────────────────
-- 샘플 도메인 테이블
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS SAMPLE (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STATUS VARCHAR(50) DEFAULT 'ACTIVE',
    AMOUNT DECIMAL(15,2) DEFAULT 0,
    PROCESSED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100)
);

-- ───────────────────────────────────────────────────────────────────────────────
-- 샘플 처리 결과 테이블
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS SAMPLE_RESULT (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SAMPLE_ID BIGINT NOT NULL,
    JOB_EXECUTION_ID BIGINT,
    RESULT_STATUS VARCHAR(50),
    RESULT_MESSAGE VARCHAR(1000),
    PROCESSED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SAMPLE_RESULT FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE(ID)
);

-- ───────────────────────────────────────────────────────────────────────────────
-- 사용자 테이블 (배치 관리자)
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(500) NOT NULL,
    EMAIL VARCHAR(200),
    ROLE VARCHAR(50) DEFAULT 'USER',
    ENABLED BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ───────────────────────────────────────────────────────────────────────────────
-- 공통 코드 그룹 테이블
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS COMMON_CODE_GROUP (
    GROUP_CODE VARCHAR(50) PRIMARY KEY,
    GROUP_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500),
    USE_YN CHAR(1) DEFAULT 'Y',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ───────────────────────────────────────────────────────────────────────────────
-- 공통 코드 테이블
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS COMMON_CODE (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GROUP_CODE VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    CODE_NAME VARCHAR(200) NOT NULL,
    CODE_VALUE VARCHAR(500),
    SORT_ORDER INT DEFAULT 0,
    USE_YN CHAR(1) DEFAULT 'Y',
    DESCRIPTION VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CODE_GROUP FOREIGN KEY (GROUP_CODE) REFERENCES COMMON_CODE_GROUP(GROUP_CODE),
    CONSTRAINT UK_COMMON_CODE UNIQUE (GROUP_CODE, CODE)
);

-- ───────────────────────────────────────────────────────────────────────────────
-- 인덱스 생성
-- ───────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS IDX_SAMPLE_STATUS ON SAMPLE(STATUS);
CREATE INDEX IF NOT EXISTS IDX_SAMPLE_PROCESSED ON SAMPLE(PROCESSED);
CREATE INDEX IF NOT EXISTS IDX_JOB_HISTORY_NAME ON BATCH_JOB_HISTORY(JOB_NAME);
CREATE INDEX IF NOT EXISTS IDX_JOB_HISTORY_STATUS ON BATCH_JOB_HISTORY(STATUS);
